# Generated by Django 5.2.1 on 2025-05-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_refresh_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_token_expires_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
