# Generated by Django 5.2.1 on 2025-05-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_spotify_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
